(use-modules (gnu packages))
(use-modules (guix profiles))
(use-modules (guix transformations))
(use-modules (gnu packages))
(use-modules (gnu packages emacs-xyz))
(define transform
(options->transformation
'(
   (without-tests . "emacs-deferred")
(with-branch . "emacs-list-utils=master")
  )))


(define-public emacs-packages
  (map (compose transform specification->package)
       '(
         "emacs-org-roam-ui"
         "emacs-nov-el"
         "emacs-elfeed"
         "emacs-guix"
         "emacs-geiser-guile"
         "emacs-aggressive-indent"
         "emacs-mini-frame"
         "emacs-vertico"
         "emacs-orderless"
         ;;    "emacs-svg-tag-mode"
         ;;   "emacs-pdf-continuous-scroll"
         "emacs-counsel"
         ;;"emacs-helpful"
         "emacs-corfu"
         "emacs-cape"
         "emacs-consult"
         "emacs-org"
         "emacs-org-download"
         "emacs-which-key"
         ;;"emacs-mu4e-alert"
         ;;"emacs-nano-modeline"
         "emacs-org-msg"
         "emacs-flycheck"
         "emacs-org-roam"
         "emacs-use-package"
         "emacs-ivy-posframe"
         "emacs-ace-link"
         "emacs-geiser-racket"
         "emacs-sudo-edit"
         ;;"emacs-guix"
         "emacs-emacsql"
         "emacs-simple-httpd"
         "emacs-websocket"
         "emacs-pdf-tools"
         "emacs-ob-async"
         "emacs-evil-collection"
         ;;    "emacs-exec-path-from-shell"
         "emacs-frames-only-mode"
         "emacs-request"
         "emacs-esxml"
         "emacs-transient"
         "emacs-multi-vterm"
         ;;"emacs-chess"
         "emacs-circe"
         ;;   "emacs-exwm"
         "emacs-all-the-icons"
         "emacs-annalist"
         ;;"emacs-auto-indent-mode"
         "emacs-bui"
         "emacs-doom-modeline"
         "emacs-all-the-icons-completion"
         "emacs-doom-themes"
         "emacs-edit-indirect"
         ;;"emacs-elisp-format"
         ;;"emacs-emms"
         ;;   "emacs-erc-image"
         ;;"emacs-evil-org"
         "emacs-org-superstar"
         "emacs-org-bullets"
         "emacs-undo-tree"
         "emacs-evil"
         "emacs-goto-chg"
         ;;"emacs-magit-popup"
         ;;"emacs-mini-modeline"
         ;;"emacs-multi-term"
         ;;"emacs-native-complete"
         ;;"emacs-org-babel-eval-in-repl"
         "emacs-ess"
         ;;"emacs-matlab-mode"
         ;;"emacs-eval-in-repl"
         "emacs-ace-window"
         "emacs-avy"
         "emacs-paredit"
         "emacs-projectile"
         "emacs-rainbow-delimiters"
         "emacs-shrink-path"
         "emacs-f"
         "emacs-dash"
                                        ;"emacs-libmpdel"
                                        ;"emacs-mpdel"
         "emacs-s"
         "emacs-tablist"
         "emacs-alect-themes"
         ;;"emacs-texfrag"
         "emacs-auctex"
         ;;"emacs-transmission"
         "emacs-windower"
         "emacs-writeroom"
         "emacs-visual-fill-column"
         ;;"emacs-xelb"
         "emacs-geiser"
         )))
(packages->manifest emacs-packages)
