(use-modules (gnu packages))
(use-modules (guix profiles))
(define-public shell-utils-packages
(list
        (specification->package "sicp")
        (specification->package "neovim")
        (specification->package "mit-scheme")
        (specification->package "mpd-mpc")
        (specification->package "glibc-locales")
        (specification->package "strace")
        (specification->package "dash")
        (specification->package "ncurses")
        (specification->package "desktop-file-utils")
        (specification->package "lm-sensors")
        (specification->package "jq")
        (specification->package "git")
        ;;(specification->package
          ;;"interception-dual-function-keys")
        ;;(specification->package "interception-tools")
        (specification->package "unoconv")
        (specification->package "cpupower")
        (specification->package "edid-decode")
        (specification->package "netcat")
        (specification->package "neofetch")
        (specification->package "pulsemixer")
        (specification->package "tree")
        (specification->package "file")
        (specification->package "alsa-utils")
        (specification->package "powertop")
        (specification->package "htop")
        (specification->package "zip")
        (specification->package "ncmpcpp")
        (specification->package "curl")
        (specification->package "wol")
        (specification->package "nmap")
        (specification->package "unzip")
        (specification->package "fzf")
        (specification->package "zlib")
        (specification->package "smartmontools")
))

(packages->manifest shell-utils-packages)
