(use-modules (gnu packages))
(use-modules (guix profiles))
(define-public window-manager-packages
(list
        (specification->package "flameshot")
        (specification->package "kanshi")
        (specification->package "rofi-wayland")
        (specification->package "slurp")
        (specification->package "waybar")
        (specification->package "grim")
        (specification->package "redshift-wayland")
        (specification->package "xorg-server-xwayland")
        (specification->package "wl-clipboard")
        (specification->package "xkill")
        (specification->package "xset")
        (specification->package "xdot")
        (specification->package "arc-theme")
        ;;(specification->package "materia-theme")
        (specification->package "orchis-theme")
        (specification->package "moka-icon-theme")
        (specification->package "qtwayland")
        (specification->package "brightnessctl")
        (specification->package "pamixer")
        (specification->package "xmodmap")
        (specification->package "setxkbmap")
))

(packages->manifest window-manager-packages)
